name: DH Lottery Automation

on:
  schedule:
    # Every Sunday at 10 AM KST (1 AM UTC)
    - cron: "0 1 * * 0"
  workflow_dispatch: # Manual execution

jobs:
  run-lottery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Setup yarn
        uses: threeal/setup-yarn-action@v2.0.0
        with:
          version: 4.10.3

      - name: Install dependencies
        run: yarn install

      - name: Install Playwright browsers
        run: yarn playwright install chromium

      - name: Build project
        run: yarn build

      - name: Run lottery automation
        run: yarn start
        env:
          DHLOTTERY_ID: ${{ secrets.DHLOTTERY_ID }}
          DHLOTTERY_PASSWORD: ${{ secrets.DHLOTTERY_PASSWORD }}
